
set -euo pipefail

PACKAGE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ORION_BASE_DIR="${ORION_BASE_DIR:-$(cd -- "$PACKAGE_DIR/.." && pwd)}"


CRAWLER_REPO="${ORION_CRAWLER_REPO:-https://github.com/Orion-Intelligence/Orion-Crawler.git}"
CRAWLER_BRANCH="${ORION_K8S_BRANCH:-kubernetes-deployment}"
CRAWLER_DIR="$ORION_BASE_DIR/Orion-Crawler"
CONFIG_DIR="${ORION_CONFIG_DIR:-/root/orion-config}"
CRAWLER_MEMORY="${ORION_CRAWLER_MEMORY:-}"

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
info() { printf '    %s\n' "$*"; }
die()  { printf '\nError: %s\n' "$*" >&2; exit 1; }

usage() {
    cat <<'EOF'
Usage: ./run.sh build kubernetics -p

  build         the only verb for now
  kubernetics   the target. `kubernetes` is accepted too.
  -p            production. Required - there is no other mode, and making it
                explicit means this cannot be run by half-typing something else.

Options:
  --crawler-memory SIZE   memory limit per crawler instance (default: sized
                          from the machine's RAM, between 4Gi and 16Gi)
  --config-dir DIR        credentials directory (default: /root/orion-config)
  --branch NAME           Orion-Crawler branch (default: kubernetes-deployment)

Environment:
  ORION_BASE_DIR          where Orion-Crawler lives or will be cloned
  ORION_K8S_BRANCH        same as --branch

What `-p` does NOT do: it does not change the application's own PRODUCTION
flag, which lives in the per-instance ConfigMaps and is edited in Rancher.
EOF
}


[[ $# -gt 0 ]] || { usage; exit 1; }
case "$1" in -h|--help) usage; exit 0 ;; esac

VERB="${1:-}"; TARGET="${2:-}"; shift 2 2>/dev/null || true
PRODUCTION=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        -p|--production)   PRODUCTION=1;       shift ;;
        --crawler-memory)  CRAWLER_MEMORY="$2"; shift 2 ;;
        --config-dir)      CONFIG_DIR="$2";     shift 2 ;;
        --branch)          CRAWLER_BRANCH="$2"; shift 2 ;;
        *) printf 'Unknown argument: %s\n\n' "$1" >&2; usage; exit 1 ;;
    esac
done

[[ "$VERB" == build ]] || { printf 'Unknown verb: %s\n\n' "${VERB:-}" >&2; usage; exit 1; }
case "$TARGET" in
    kubernetics|kubernetes) ;;
    *) printf 'Unknown target: %s\n\n' "${TARGET:-}" >&2; usage; exit 1 ;;
esac
(( PRODUCTION )) || { printf '%s\n\n' '-p is required.' >&2; usage; exit 1; }


step "Preflight"

[[ "$(id -u)" == 0 ]] || die "run as root - k3s installs a systemd service: sudo $0 $VERB $TARGET -p"

for binary in git curl python3; do
    command -v "$binary" >/dev/null || die "'$binary' is required but not installed. Run ./setup.sh first."
done
info "host tools present"

if [[ -n "$CRAWLER_MEMORY" ]]; then
    info "crawler memory ${CRAWLER_MEMORY} (given)"
else
    live=""
    if command -v kubectl >/dev/null && [[ -f /etc/rancher/k3s/k3s.yaml ]]; then
        live="$(KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl get statefulset orion-crawler -n orion \
            -o jsonpath='{.spec.template.spec.containers[?(@.name=="worker")].resources.limits.memory}' 2>/dev/null || true)"
    fi
    if [[ -n "$live" ]]; then
        CRAWLER_MEMORY="$live"
        info "crawler memory ${CRAWLER_MEMORY} (keeping what the cluster already runs)"
    else
        total_gb="$(awk '/MemTotal/ {printf "%d", $2/1024/1024}' /proc/meminfo)"
        sized=$(( total_gb / 8 ))
        (( sized < 4 ))  && sized=4
        (( sized > 16 )) && sized=16
        CRAWLER_MEMORY="${sized}Gi"
        info "crawler memory ${CRAWLER_MEMORY} (new cluster, sized from ${total_gb}Gi of RAM)"
    fi
fi


step "Credentials"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"


copy_from_package() {
    local module="$1" target="$CONFIG_DIR/$2" source="$PACKAGE_DIR/pull/$1/.env"
    [[ -f "$target" ]] && return 0
    [[ -f "$source" ]] || return 0
    install -m 600 "$source" "$target"
    info "$2 taken from pull/$module/.env"
}
copy_from_package Orion-Micros     micros.env
copy_from_package Orion-Dark-Nexus nexus.env

missing=()
for f in crawler.env micros.env nexus.env dockerhub.env; do
    [[ -f "$CONFIG_DIR/$f" ]] || missing+=("$f")
done

if (( ${#missing[@]} )); then
    printf '\nMissing credential files in %s:\n' "$CONFIG_DIR" >&2
    printf '    %s\n' "${missing[@]}" >&2
    printf '\n' >&2
    for f in "${missing[@]}"; do
        case "$f" in
            crawler.env)
                printf 'crawler.env holds the crawler Secret. If this machine already ran the\n' >&2
                printf 'Docker stack, copy the .env from that checkout:\n' >&2
                printf '    cp %s/.env %s/crawler.env\n\n' "$CRAWLER_DIR" "$CONFIG_DIR" >&2 ;;
            micros.env|nexus.env)
                printf '%s is normally generated by this package. Run:\n    ./setup.sh\n' "$f" >&2
                printf 'and choose the matching module, then run this again.\n\n' >&2 ;;
            dockerhub.env)
                printf 'dockerhub.env holds a Docker Hub access token - the Orion images are in a\n' >&2
                printf 'private repository. Create it without leaving the token in your shell\n' >&2
                printf 'history:\n' >&2
                printf "    read -p 'Docker Hub username: ' U && read -s -p 'Docker Hub token: ' T && echo \\\\\n" >&2
                printf "      && printf 'DOCKERHUB_USERNAME=%%s\\\\nDOCKERHUB_TOKEN=%%s\\\\n' \"\$U\" \"\$T\" > %s/dockerhub.env \\\\\n" "$CONFIG_DIR" >&2
                printf '      && chmod 600 %s/dockerhub.env && unset T U\n\n' "$CONFIG_DIR" >&2 ;;
        esac
    done
    die "fill in the files above, then run this again. Nothing has been changed."
fi
chmod 600 "$CONFIG_DIR"/*.env
info "all four credential files present"


step "Orion-Crawler ($CRAWLER_BRANCH)"


git_auth() { python3 -B "$PACKAGE_DIR/_shared/github_git.py" "$@"; }

if [[ -d "$CRAWLER_DIR/.git" ]]; then
    info "updating $CRAWLER_DIR"
    git_auth -C "$CRAWLER_DIR" fetch --depth 1 origin "+${CRAWLER_BRANCH}:refs/remotes/origin/${CRAWLER_BRANCH}" \
        || die "could not fetch $CRAWLER_BRANCH"
 
    git -C "$CRAWLER_DIR" reset --hard "origin/${CRAWLER_BRANCH}"
    git -C "$CRAWLER_DIR" clean -fd
else
    info "cloning into $CRAWLER_DIR"
    git_auth clone --depth 1 --branch "$CRAWLER_BRANCH" "$CRAWLER_REPO" "$CRAWLER_DIR" \
        || die "could not clone Orion-Crawler"
fi
info "at $(git -C "$CRAWLER_DIR" log -1 --format='%h %s')"

BOOTSTRAP="$CRAWLER_DIR/k8s/bootstrap.sh"
[[ -f "$BOOTSTRAP" ]] || die "k8s/bootstrap.sh not found in $CRAWLER_DIR.
Branch '$CRAWLER_BRANCH' may not be the one carrying the Kubernetes work."


step "Deploying"
info "handing over to k8s/bootstrap.sh - everything below comes from it"
echo

bash "$BOOTSTRAP" --config-dir "$CONFIG_DIR" --crawler-memory "$CRAWLER_MEMORY"
