#!/usr/bin/env python3
import json
import sys

from session import request


def main():
    action = sys.argv[1]
    if action == 'store':
        value = json.load(sys.stdin)
        request('set', 'docker:' + value['ServerURL'], value)
    elif action == 'get':
        server = sys.stdin.read().strip()
        value = request('get', 'docker:' + server)
        if not value:
            print('credentials not found in native keychain')
            return 1
        print(json.dumps({'ServerURL': server, 'Username': value['Username'], 'Secret': value['Secret']}))
    elif action == 'erase':
        request('delete', 'docker:' + sys.stdin.read().strip())
    elif action == 'list':
        print('{}')
    else:
        return 1
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError, IndexError):
        print('In-memory Docker credential session unavailable', file=sys.stderr)
        sys.exit(1)
